name = "treasurenet-docs"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./build"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Environment configurations
[env.staging]
name = "treasurenet-docs-staging"

[env.production]
name = "treasurenet-docs"