name: Docusaurus Deploy

on:
  push:
    branches:
      - feature/1.0.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: 16
      - run: npm install
      - run: npm run build

      - name: Deploy to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}

          connect_timeout: 180s

          scp: |
            ./build/* => /data/docs/build/

